### ISSUE TITLE
翻译Ionic 官方文档

### ISSUE THREAD

**Issue by aspojo** [angelofan/timesince.js#1]
最近我在翻译Ionic 官方文档，感觉一个人做的太累了，看到之前你也翻译过不少内容。想看看，你是否有兴趣继续翻译下去，这样我们就有可能尽快把中文文档翻译完成。

**Comment by angelofan** [comment]
好的，可以

**Comment by angelofan** [comment]
前几年我就开始了ionic文档的翻译，但是经常忘记继续翻译，我记得当时翻译到了80%左右，然后就一直忘记继续翻译了。随后ionic不断的更新迭代，到现在，ionic文档翻译进度跌到了50%，我觉得以我们两个人的进度，很难跟得上ionic的文档更新频率。我看到你在ionic社区翻译网站也开启了一个讨论问官方多久才能显示中文翻译。我觉得ionic对于中国市场并不活跃，ionic文档网站现在显示了日本语言，主要是因为他们在日本有办事处，并且他们专门为日本开设了分站 https://ionicframework.jp/ ,不知道ionic官网对中国市场的计划是什么样的，这也就影响了ionic对于中文翻译的在乎与否。当时我为[iro.js](https://crowdin.com/project/irojs) 翻译的时候，开源库的作者回复很快，而且我翻译完成以后过几天就在文档网站显示中文了。我们现在翻译并没有官方的人跟进，所以感觉就算我们翻译完了，他们还有很多校对等工作要做，到时候也不一定很快上线中文翻译，随着时间推移版本迭代，文档翻译的进度就有下跌了，就又不了了之了。。。我对此也很无奈。

**Comment by aspojo** [comment]
明白了，感谢这么专业的解读。
